name: goreleaser

on:
  create:
    tags:
      - v*

jobs:
  release:
    name: Cut Release
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Go
        uses: actions/setup-go@v1
      -
        name: Checkout
        uses: actions/checkout@v1
        
      - 
        name: Validates GO releaser config
        uses: docker://goreleaser/goreleaser:latest
        with:
          args: check

      - 
        name: Create release on GitHub
        uses: docker://goreleaser/goreleaser:latest
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{secrets.GORELEASER_GITHUB_TOKEN}}
